# Generated by Django 3.2.5 on 2021-08-06 10:15

import UserModel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(upload_to=UserModel.models.avatar_path, verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='personal_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('energy', models.CharField(max_length=20)),
                ('healthy', models.CharField(max_length=20)),
                ('happy', models.CharField(max_length=20)),
                ('Hunger', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usersession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('sessionid', models.CharField(max_length=32)),
            ],
        ),
    ]
