# Generated by Django 3.2.4 on 2021-09-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_attributes',
            name='Hunger',
            field=models.CharField(max_length=20, verbose_name='饥饿'),
        ),
        migrations.AlterField(
            model_name='personal_attributes',
            name='energy',
            field=models.CharField(max_length=20, verbose_name='精力'),
        ),
        migrations.AlterField(
            model_name='personal_attributes',
            name='happy',
            field=models.CharField(max_length=20, verbose_name='快乐'),
        ),
        migrations.AlterField(
            model_name='personal_attributes',
            name='healthy',
            field=models.CharField(max_length=20, verbose_name='健康'),
        ),
    ]
