# Generated by Django 3.2.4 on 2021-07-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='speech',
        ),
    ]
