# Generated by Django 3.2.4 on 2021-09-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input_Recipe_Material',
            new_name='Input_Recipe_Diet',
        ),
    ]
