# Generated by Django 3.2.4 on 2021-09-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_recipe',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DietModel.treatment_diet', verbose_name='烹饪方法'),
        ),
    ]
