# Generated by Django 3.2.4 on 2021-10-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_recipe',
            name='taste_description',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
