# Generated by Django 3.2.4 on 2021-09-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diet_materialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')], default=1, verbose_name='食材等级')),
                ('health', models.FloatField(verbose_name='健康度')),
                ('Satiety', models.FloatField(verbose_name='饱食度')),
                ('salty', models.FloatField(verbose_name='咸')),
                ('sweet', models.FloatField(verbose_name='甜')),
                ('bitterness', models.FloatField(verbose_name='苦')),
                ('aroma', models.FloatField(verbose_name='味道度')),
                ('r_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DietModel.diet_material', verbose_name='食品')),
            ],
        ),
    ]
