# Generated by Django 3.2.4 on 2021-09-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0002_rename_input_recipe_material_input_recipe_diet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet_recipe',
            old_name='Owner',
            new_name='owner',
        ),
    ]
