# Generated by Django 3.2.4 on 2021-09-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0003_auto_20210921_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='diet_recipes',
        ),
    ]
