# Generated by Django 3.2.5 on 2021-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0003_rename_owner_diet_recipe_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_recipe',
            name='name',
            field=models.CharField(default=' ', max_length=50, verbose_name='食谱名'),
        ),
    ]
