# Generated by Django 3.2.4 on 2021-09-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0005_input_recipe_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_recipe_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DietModel.diet_materialdetail', verbose_name='输入物资'),
        ),
        migrations.AlterUniqueTogether(
            name='diet_materialdetail',
            unique_together={('r_material', 'level')},
        ),
    ]
