# Generated by Django 3.2.4 on 2021-09-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DietModel', '0006_auto_20210921_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='diet_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50, verbose_name='名字')),
                ('Owner', models.IntegerField(db_index=True, default=' ', verbose_name='拥有者')),
                ('health', models.FloatField(default=0.0, verbose_name='健康度')),
                ('Satiety', models.FloatField(default=0.0, verbose_name='饱食度')),
                ('acid', models.FloatField(default=0.0, verbose_name='酸')),
                ('salty', models.FloatField(default=0.0, verbose_name='咸')),
                ('sweet', models.FloatField(default=0.0, verbose_name='甜')),
                ('bitterness', models.FloatField(default=0.0, verbose_name='苦')),
                ('aroma', models.FloatField(default=0.0, verbose_name='味道度')),
                ('input', models.ManyToManyField(related_name='input', through='DietModel.Input_Recipe_Material', to='DietModel.diet_materialDetail', verbose_name='输入')),
            ],
        ),
        migrations.DeleteModel(
            name='diet_recipes',
        ),
        migrations.AlterField(
            model_name='input_recipe_material',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DietModel.diet_recipe', verbose_name='配方id'),
        ),
    ]
