# Generated by Django 3.2.5 on 2021-10-02 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_contact_from_person', to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_contact_to_person', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
        ),
    ]
