# Generated by Django 3.2.5 on 2021-10-02 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialContactModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_from_person', to=settings.AUTH_USER_MODEL, verbose_name='发起者'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_to_person', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.CreateModel(
            name='Social_behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_value_change', models.IntegerField()),
                ('type', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_behavior_from_person', to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_behavior_to_person', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
        ),
    ]
