# Generated by Django 3.2.5 on 2021-08-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
