# Generated by Django 3.2.5 on 2021-08-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechModel', '0004_speech_speech_attitude_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech_attitude',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='speech_attitude',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='speech',
        ),
        migrations.DeleteModel(
            name='speech',
        ),
        migrations.DeleteModel(
            name='speech_attitude',
        ),
        migrations.DeleteModel(
            name='topic',
        ),
    ]
