# Generated by Django 3.2.5 on 2021-08-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SpeechModel', '0005_auto_20210810_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cheer', models.IntegerField(default=0)),
                ('onlooker', models.IntegerField(default=0)),
                ('catcall', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=1000)),
                ('speech', models.ManyToManyField(to='SpeechModel.Speech')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAttitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', models.SmallIntegerField(choices=[(1, '欢呼'), (2, '关注'), (3, '倒彩')])),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeechModel.speech')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
