# Generated by Django 3.2.5 on 2021-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogModel', '0002_auto_20210925_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateField(),
        ),
    ]
