# Generated by Django 3.2.5 on 2021-08-07 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='物资id')),
                ('name', models.CharField(max_length=20, verbose_name='物资名')),
                ('weight', models.FloatField(verbose_name='权重')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_count', models.FloatField(verbose_name='所需数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='MaterialModel.material', verbose_name='物资id')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material', to='MaterialModel.material', verbose_name='所需物品id')),
            ],
        ),
    ]
