# Generated by Django 3.2.5 on 2021-08-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='MaterialModel.material', verbose_name='物资'),
        ),
        migrations.CreateModel(
            name='UserMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='拥有数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material', verbose_name='拥有物资')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
