# Generated by Django 3.2.5 on 2021-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0002_auto_20210807_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='level',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='物资等级'),
        ),
    ]
