# Generated by Django 3.2.5 on 2021-08-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0003_material_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='level',
        ),
        migrations.RemoveField(
            model_name='material',
            name='weight',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material', to='MaterialModel.material', verbose_name='所需物资id'),
        ),
        migrations.CreateModel(
            name='MaterialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity', models.FloatField(verbose_name='物资自身产能')),
                ('level', models.SmallIntegerField(default=1, verbose_name='物资等级')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.material', verbose_name='拥有物资')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='material_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material_detail', to='MaterialModel.materialdetail', verbose_name='物资等级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='raw_material_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_detail', to='MaterialModel.materialdetail', verbose_name='所需物资等级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermaterial',
            name='material_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.materialdetail', verbose_name='物资等级'),
            preserve_default=False,
        ),
    ]
