# Generated by Django 3.2.5 on 2021-08-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0005_alter_materialdetail_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdetail',
            name='material',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='material',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='material_detail',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='raw_material_detail',
        ),
        migrations.RemoveField(
            model_name='usermaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='usermaterial',
            name='material_detail',
        ),
        migrations.RemoveField(
            model_name='usermaterial',
            name='user',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialDetail',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='UserMaterial',
        ),
    ]
