# Generated by Django 3.2.5 on 2021-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0007_material_materialdetail_recipe_usermaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='物资id'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='物资名'),
        ),
    ]
