# Generated by Django 3.2.5 on 2021-08-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0008_auto_20210807_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='recipe',
            name='produce_count',
            field=models.FloatField(default=1, verbose_name='产出物资数量'),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '等级1'), (2, '等级2'), (3, '等级3')], default=1, verbose_name='物资等级'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='material_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_detail', to='MaterialModel.materialdetail', verbose_name='产出详情'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='raw_material_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_detail', to='MaterialModel.materialdetail', verbose_name='所需物资详情'),
        ),
        migrations.AlterField(
            model_name='usermaterial',
            name='material_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialModel.materialdetail', verbose_name='物资详情'),
        ),
        migrations.AlterUniqueTogether(
            name='materialdetail',
            unique_together={('material', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('material_detail', 'raw_material_detail')},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='material',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='raw_material',
        ),
    ]
