# Generated by Django 3.2.5 on 2021-08-08 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialModel', '0009_auto_20210807_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdetail',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')], default=1, verbose_name='物资等级'),
        ),
        migrations.AlterUniqueTogether(
            name='usermaterial',
            unique_together={('user', 'material_detail')},
        ),
    ]
