# Generated by Django 3.2.5 on 2021-08-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0010_auto_20210808_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='物资id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
