# Generated by Django 3.2.5 on 2021-08-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0011_auto_20210808_2243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialdetail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='materialdetail',
            name='material',
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='material_detail',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='raw_material_detail',
        ),
        migrations.AlterUniqueTogether(
            name='usermaterial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usermaterial',
            name='material_detail',
        ),
        migrations.RemoveField(
            model_name='usermaterial',
            name='user',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialDetail',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='UserMaterial',
        ),
    ]
