# Generated by Django 3.2.5 on 2021-08-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialModel', '0016_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input_recipe_material',
            options={'verbose_name_plural': '所需物资表'},
        ),
        migrations.AlterModelOptions(
            name='output_recipe_material',
            options={'verbose_name_plural': '产出物资表'},
        ),
    ]
