# Generated by Django 3.2.5 on 2021-07-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='uid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
