# Generated by Django 3.2.4 on 2021-07-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_speech_attitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('energy', models.CharField(max_length=20)),
                ('healthy', models.CharField(max_length=20)),
                ('happy', models.CharField(max_length=20)),
                ('Hunger', models.CharField(max_length=20)),
            ],
        ),
    ]
