# Generated by Django 3.2.5 on 2021-07-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(upload_to='avatar', verbose_name='头像'),
        ),
    ]
