# Generated by Django 3.2.4 on 2021-09-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesModel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raw_material',
        ),
    ]
