# Generated by Django 3.2.4 on 2021-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_materialDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.SmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3')], default=1, verbose_name='食材等级')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('health', models.FloatField(verbose_name='健康度')),
                ('Satiety', models.FloatField(verbose_name='饱食度')),
                ('salty', models.FloatField(verbose_name='咸')),
                ('sweet', models.FloatField(verbose_name='甜')),
                ('bitterness', models.FloatField(verbose_name='苦')),
                ('aroma', models.FloatField(verbose_name='苦')),
            ],
        ),
    ]
