# Generated by Django 3.2.4 on 2021-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesModel', '0002_raw_materialdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.IntegerField(unique=True, verbose_name='食材id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='食材名')),
            ],
        ),
    ]
