# Generated by Django 3.2.4 on 2021-09-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesModel', '0003_raw_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_materialDetail_2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('r_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesModel.raw_material', verbose_name='食品')),
            ],
        ),
    ]
