# Generated by Django 3.2.4 on 2021-09-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesModel', '0005_auto_20210918_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_material',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='食材名'),
        ),
        migrations.DeleteModel(
            name='Raw_materialDetail_3',
        ),
    ]
