# Generated by Django 3.2.4 on 2021-09-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesModel', '0007_input_recipe_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_materialdetail',
            name='r_material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RecipesModel.raw_material', verbose_name='食品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input_recipe_material',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RecipesModel.raw_materialdetail', verbose_name='输入物资'),
        ),
    ]
