# Generated by Django 3.2.4 on 2021-09-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesModel', '0008_auto_20210918_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='input',
            field=models.ManyToManyField(related_name='input', through='RecipesModel.Input_Recipe_Material', to='RecipesModel.Raw_materialDetail', verbose_name='输入'),
        ),
    ]
