# Generated by Django 3.2.5 on 2021-08-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0005_auto_20210802_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='farming',
            name='user',
        ),
        migrations.RemoveField(
            model_name='husbandry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='building',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='cutting',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='farming',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='husbandry',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='processing',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='social',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.DeleteModel(
            name='building',
        ),
        migrations.DeleteModel(
            name='cutting',
        ),
        migrations.DeleteModel(
            name='farming',
        ),
        migrations.DeleteModel(
            name='husbandry',
        ),
        migrations.DeleteModel(
            name='processing',
        ),
        migrations.DeleteModel(
            name='social',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
        migrations.DeleteModel(
            name='vehicle',
        ),
    ]
