# Generated by Django 3.2.5 on 2021-08-02 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SkillModel', '0008_auto_20210802_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='construct',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('skill_num', models.FloatField(default=0)),
                ('building', models.FloatField(default=0)),
                ('mending', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cutting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='farming',
            name='id',
        ),
        migrations.RemoveField(
            model_name='husbandry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='social',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='building',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='cutting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farming',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='husbandry',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='social',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='building',
        ),
        migrations.AddField(
            model_name='userskill',
            name='construct',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.construct'),
            preserve_default=False,
        ),
    ]
