# Generated by Django 3.2.5 on 2021-08-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0009_auto_20210802_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='construct',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.construct', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='cutting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.cutting', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='farming',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.farming', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='husbandry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.husbandry', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='processing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.processing', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='social',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.social', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.vehicle', to_field='user_id'),
        ),
    ]
