# Generated by Django 3.2.5 on 2021-08-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0014_construct_cutting_farming_husbandry_processing_social_userskill_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cutting',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='farming',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='husbandry',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='processing',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='social',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
    ]
