# Generated by Django 3.2.4 on 2021-08-15 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_id', models.SmallIntegerField(verbose_name='大类id')),
                ('big_name', models.CharField(max_length=20, verbose_name='大类名称')),
                ('small_id', models.SmallIntegerField(blank=True, null=True, verbose_name='大类下的小类id')),
                ('small_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='小类名称')),
                ('db_big_name', models.CharField(default='0', max_length=20, verbose_name='大类表名')),
                ('db_small_name', models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='小类表名')),
            ],
        ),
        migrations.CreateModel(
            name='UserSmallSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liangshi', models.FloatField(default=0, verbose_name='耕作——粮食种植技能点')),
                ('suguo', models.FloatField(default=0, verbose_name='耕作——蔬果种植技能点')),
                ('jingji', models.FloatField(default=0, verbose_name='耕作——经济作物种植技能点')),
                ('kaiken', models.FloatField(default=0, verbose_name='耕作——开垦技能点')),
                ('caiji', models.FloatField(default=0, verbose_name='采伐——采集技能点')),
                ('famu', models.FloatField(default=0, verbose_name='采伐——伐木技能点')),
                ('kaicai', models.FloatField(default=0, verbose_name='采伐——开采技能点')),
                ('kantan', models.FloatField(default=0, verbose_name='采伐——勘探技能点')),
                ('jianzhu', models.FloatField(default=0, verbose_name='建设——建筑技能点')),
                ('xiushan', models.FloatField(default=0, verbose_name='建设——修缮技能点')),
                ('yelian', models.FloatField(default=0, verbose_name='加工——冶炼技能点')),
                ('jinsu', models.FloatField(default=0, verbose_name='加工——金属锻造技能点')),
                ('fangzhi', models.FloatField(default=0, verbose_name='加工——纺织技能点')),
                ('shiping', models.FloatField(default=0, verbose_name='加工——食品加工技能点')),
                ('mushi', models.FloatField(default=0, verbose_name='加工——木石加工技能点')),
                ('xiongbian', models.FloatField(default=0, verbose_name='社交——雄辩技能点')),
                ('jiaoji', models.FloatField(default=0, verbose_name='社交——交际技能点')),
                ('wenshu', models.FloatField(default=0, verbose_name='社交——文书技能点')),
                ('guanli', models.FloatField(default=0, verbose_name='社交——管理技能点')),
                ('lushang', models.FloatField(default=0, verbose_name='舟车——陆上运输技能点')),
                ('shuishang', models.FloatField(default=0, verbose_name='舟车——水上运输技能点')),
                ('bulao', models.FloatField(default=0, verbose_name='舟车——捕捞技能点')),
                ('shoulie', models.FloatField(default=0, verbose_name='畜牧——狩猎技能点')),
                ('jiaqin', models.FloatField(default=0, verbose_name='畜牧——家禽养殖技能点')),
                ('jiachu', models.FloatField(default=0, verbose_name='畜牧——家畜养殖技能点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBigSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gengzuo', models.FloatField(default=0, verbose_name='耕作技能点')),
                ('gengzuo_level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='耕作等级')),
                ('caifa', models.FloatField(default=0, verbose_name='采伐技能点')),
                ('caifa_level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='采伐等级')),
                ('jianshe', models.FloatField(default=0, verbose_name='建设技能点')),
                ('jianshe_level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='建设等级')),
                ('jiagong', models.FloatField(default=0, verbose_name='加工技能点')),
                ('jiagong_level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='加工等级')),
                ('shejiao', models.FloatField(default=0, verbose_name='社交技能点')),
                ('shejiao_level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='社交等级')),
                ('zhouche', models.FloatField(default=0, verbose_name='舟车技能点')),
                ('zhouche_level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='舟车等级')),
                ('xumu', models.FloatField(default=0, verbose_name='畜牧技能点')),
                ('xumu_level', models.SmallIntegerField(choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], default=1, verbose_name='畜牧等级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
