# Generated by Django 3.2.4 on 2021-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbigskill',
            name='caifa_wuxing',
            field=models.FloatField(default=0, verbose_name='采伐悟性'),
        ),
        migrations.AddField(
            model_name='userbigskill',
            name='gengzuo_wuxing',
            field=models.FloatField(default=0, verbose_name='耕作悟性'),
        ),
        migrations.AddField(
            model_name='userbigskill',
            name='jiagong_wuxing',
            field=models.FloatField(default=0, verbose_name='加工悟性'),
        ),
        migrations.AddField(
            model_name='userbigskill',
            name='jianshe_wuxing',
            field=models.FloatField(default=0, verbose_name='建设悟性'),
        ),
        migrations.AddField(
            model_name='userbigskill',
            name='shejiao_wuxing',
            field=models.FloatField(default=0, verbose_name='社交悟性'),
        ),
        migrations.AddField(
            model_name='userbigskill',
            name='xumu_wuxing',
            field=models.FloatField(default=0, verbose_name='畜牧悟性'),
        ),
        migrations.AddField(
            model_name='userbigskill',
            name='zhouche_wuxing',
            field=models.FloatField(default=0, verbose_name='舟车悟性'),
        ),
    ]
