# Generated by Django 3.2.5 on 2021-08-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0004_auto_20210802_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farming',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='husbandry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
