# Generated by Django 3.2.5 on 2021-08-02 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('SkillModel', '0006_auto_20210802_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_num', models.FloatField(default=0)),
                ('building', models.FloatField(default=0)),
                ('mending', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cutting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_num', models.FloatField(default=0)),
                ('collection', models.FloatField(default=0)),
                ('lumbering', models.FloatField(default=0)),
                ('exploitation', models.FloatField(default=0)),
                ('prospecting', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='farming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_num', models.FloatField(default=0)),
                ('grain', models.FloatField(default=0)),
                ('vegetables_fruit', models.FloatField(default=0)),
                ('cash_crops', models.FloatField(default=0)),
                ('reclaim', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='husbandry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_num', models.FloatField(default=0)),
                ('hunt', models.FloatField(default=0)),
                ('fowl', models.FloatField(default=0)),
                ('livestock', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='processing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_num', models.FloatField(default=0)),
                ('smelt', models.FloatField(default=0)),
                ('forge', models.FloatField(default=0)),
                ('spin', models.FloatField(default=0)),
                ('food_processing', models.FloatField(default=0)),
                ('wood_stone_processing', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_num', models.FloatField(default=0)),
                ('eloquence', models.FloatField(default=0)),
                ('communicate', models.FloatField(default=0)),
                ('write', models.FloatField(default=0)),
                ('manage', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_num', models.FloatField(default=0)),
                ('land_transport', models.FloatField(default=0)),
                ('water_transport', models.FloatField(default=0)),
                ('fishing', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.building')),
                ('cutting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.cutting')),
                ('farming', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.farming')),
                ('husbandry', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.husbandry')),
                ('processing', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.processing')),
                ('social', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.social')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SkillModel.vehicle')),
            ],
        ),
    ]
