# Generated by Django 3.2.5 on 2021-08-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0016_auto_20210808_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallskill',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='big_skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='small_skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='BigSkill',
        ),
        migrations.DeleteModel(
            name='SmallSkill',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
