# Generated by Django 3.2.5 on 2021-08-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SkillModel', '0018_bigskill_smallskill_userskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='big_level',
            field=models.SmallIntegerField(blank=True, choices=[(1, '学徒'), (2, '匠人'), (3, '匠师'), (4, '专家'), (5, '大师'), (6, '宗师'), (7, '大宗师')], null=True, verbose_name='大类技能等级'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='big_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SkillModel.bigskill', verbose_name='大类技能'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='big_skillnum',
            field=models.FloatField(blank=True, null=True, verbose_name='大类技能点'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='small_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SkillModel.smallskill', verbose_name='小类技能'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='small_skillnum',
            field=models.FloatField(blank=True, null=True, verbose_name='小类技能点'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'big_skill', 'small_skill')},
        ),
    ]
