# Generated by Django 3.2.5 on 2021-08-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0023_bigskill_smallskill_userskill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smallskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='smallskill',
            name='sub',
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='big_skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='small_skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='BigSkill',
        ),
        migrations.DeleteModel(
            name='SmallSkill',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
