# Generated by Django 3.2.5 on 2021-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillModel', '0026_auto_20210808_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillname',
            name='db_big_name',
            field=models.CharField(default='0', max_length=20, verbose_name='大类表名'),
        ),
        migrations.AddField(
            model_name='skillname',
            name='db_small_name',
            field=models.CharField(default='0', max_length=20, verbose_name='小类表名'),
        ),
        migrations.AlterField(
            model_name='skillname',
            name='small_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='大类下的小类id'),
        ),
        migrations.AlterField(
            model_name='skillname',
            name='small_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='小类名称'),
        ),
    ]
