# Generated by Django 3.2.5 on 2021-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sideline_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('number_of_today_sideline', models.PositiveIntegerField(verbose_name='单日副业次数')),
                ('sideline_day_c', models.CharField(max_length=20, verbose_name='最新的副业日期,civ时间制')),
                ('sideline_day', models.CharField(max_length=30, verbose_name='最新的副业日期,正常时间制')),
                ('number_of_all_sideline', models.CharField(max_length=30, verbose_name='总副业次数')),
                ('every_sideline_all', models.JSONField(verbose_name='每种副业总次数')),
            ],
        ),
        migrations.CreateModel(
            name='sideline_work',
            fields=[
                ('sideline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sideline_name', models.CharField(max_length=50, verbose_name='副业名字')),
                ('sideline_bigskills', models.CharField(max_length=100, verbose_name='使用的技能大类 dbname，以空格隔开')),
                ('sideline_smallskills', models.CharField(max_length=100, verbose_name='使用的技能小类 dbname，以空格隔开，如果没有适用的技能小类，设置为0，与大类对应')),
                ('sideline_coefficient', models.CharField(max_length=100, verbose_name='各自技能对应的产能加成，以空格隔开')),
                ('sideline_product', models.CharField(max_length=100, verbose_name='副业产出物品id，以空格隔开')),
                ('sideline_product_probability', models.CharField(max_length=100, verbose_name='副业产出物品的各比例。以空格隔开')),
                ('sideline_skills_increase', models.CharField(max_length=100, verbose_name='各技能增长修正，以空格隔开，不设置默认为1，设置需要全部都设置')),
                ('sideline_happy', models.CharField(max_length=20, verbose_name='快乐消耗,不设置默认15')),
                ('sideline_health', models.CharField(max_length=20, verbose_name='健康消耗,不设置默认15')),
                ('sideline_energy', models.CharField(max_length=20, verbose_name='精力消耗,不设置默认15')),
                ('c_type', models.IntegerField(verbose_name='产能算法种类,0:上设系数算法，1:通用产能算法')),
            ],
        ),
        migrations.CreateModel(
            name='work_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('work_id', models.CharField(max_length=20)),
                ('work_station_id', models.CharField(max_length=20)),
                ('work_date', models.CharField(max_length=20)),
            ],
        ),
    ]
